### ISSUE TITLE
about link rot

### ISSUE THREAD

**Issue by lyan6** [genenetwork/genenetwork#14]
[From Rob email]

We have a bit of "link rot" to fix in GN1. Link rot means that our external links from GN1 stop working properly (they have rotten or rusted).

Here is an example for the gene symbol Cyp2c44:

Inline image 1

Gene:  This link works great
HomoloGene: works great
USCS: works well, but link might be better if it went straight to the gene map like this:

http://genome.cse.ucsc.edu/cgi-bin/hgTracks?db=mm9&position=chr19%3A44079512-44103737&hgsid=435526141_Ax12Q5pBVNZYJ6JfBHu7I6TL2NcX

BioGPS: works great
STRING:  Link rot
Should go to new page for CYP2C44. I'm not sure that the URL should be any more. But STRING is great and we should like

PANTHER:  Link rot
Should go to http://www.pantherdb.org/genes/geneList.do?searchType=basic&fieldName=all&organism=all&listType=1&fieldValue=cyp2c44

Gemma:  works great

SynDB:  We should remove this link. It is only good for a small number of genes (that associated with the synapses of neurons). Could replace with 

Two New Links TO ADD:

EBI GWAS:  with this type of search URL https://www.ebi.ac.uk/gwas/search?query=got1
where the query term is the gene symbol "got1" in this case

GeneMania: http://www.genemania.org
Here you need to provide the species and the gene symbol. Not sure how to do this. They have five species that we also have (Arabidopsis, human, rat, mouse, and Drosophila)

**Comment by leiyan** [comment]
Test.

Lei Yan
IT Administrator IV
Center for Integrative and Translational Genomics
The University of Tennessee Health Science Center

**Comment by lyan6** [comment]
Test 2.

**Comment by lyan6** [comment]
test

**Comment by lyan6** [comment]
test111

**Comment by sn3twork** [comment]
I will write a script to identify all broken links in the next couple of days.

**Comment by lyan6** [comment]
Last test.

**Comment by robwwilliams** [comment]
Great, thanks.

**Comment by robwwilliams** [comment]
Dear Ethan,

Fabulous. Thanks. Let me know if you need any input.

On Tue, Jul 21, 2015 at 11:31 AM, Ethan Willis <notifications@github.com>
wrote:

> I will write a script to identify all broken links in the next couple of
> days.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/genenetwork/genenetwork/issues/14#issuecomment-123393849>
> .
>



-- 
Rob

Robert W. Williams, Ph.D.
UT-ORNL Governor's Chair in Computational Genomics
Chair, Department of Genetics, Genomics and Informatics
University of Tennessee Health Science Center
Room 501
855 Monroe Avenue, Memphis TN 38163 USA

Office 901 448-7018  CELL 901 604 4752
Office: 501 Wittenborg Building
Department of Genetics: 71 Manassas St, Memphis TN 38163
EMAIL: rwilliams@uthsc.edu
Alternative email: labwilliams@gmail.com
SKYPE: robwwilliams

**Comment by lyan6** [comment]
[Gene]
old:
http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?db=gene&cmd=Retrieve&dopt=Graphics&list_uids=226143
new:
http://www.ncbi.nlm.nih.gov/gene?cmd=Retrieve&dopt=Graphics&list_uids=226143

[HomoloGene]
old:
http://www.ncbi.nlm.nih.gov/sites/entrez?Db=homologene&Cmd=DetailsSearch&Term=115563
new:
http://www.ncbi.nlm.nih.gov/homologene/?term=115563

[UCSC]
old:
http://genome.cse.ucsc.edu/cgi-bin/hgGene?db=mm9&hgg_gene=NM_001001446&hgg_chrom=chr19&hgg_start=44079511&hgg_end=44103689
new:
http://genome.cse.ucsc.edu/cgi-bin/hgTracks?db=mm9&hgg_gene=NM_001001446&hgg_chrom=chr19&hgg_start=44079511&hgg_end=44103689

[STRING]
old:
http://string.embl.de/newstring_cgi/show_link_summary.pl?identifier=Cyp2c44
new:
http://string-db.org/newstring_cgi/show_network_section.pl?identifier=Cyp2c44

[PANTHER]
old:
http://www.pantherdb.org/genes/gene.do?acc=226143
new:
http://www.pantherdb.org/genes/geneList.do?searchType=basic&fieldName=all&organism=all&listType=1&fieldValue=Cyp2c44

[ABA]
old:
http://mouse.brain-map.org/brain/Cyp2c44.html
new:
http://mouse.brain-map.org/search/show?search_type=gene&search_term=Cyp2c44

[EBI GWAS]
new:
https://www.ebi.ac.uk/gwas/search?query=Cyp2c44

**Comment by lyan6** [comment]
https://github.com/genenetwork/genenetwork/commit/5733426b9c061194432cbba47ccb82817a0ddd86
