### ISSUE TITLE
specify the dataset name when I do a Batch Submission

### ISSUE THREAD

**Issue by leiyan** [genenetwork/genenetwork#20]
[From Emails]

How do I specify the dataset name when I do a Batch Submission? It is assigned “Temp”by default, and I’m not sure how to change this. Please see attached screenshot. Your help would be greatly appreciated.

When I plot a heatmap of the data with traits clustered, the dendrogram labels contain "Temp" as their prefix, which looks a little strange if used in a publication. That's the reason behind this request.

**Comment by lyan6** [comment]
Fixed.

Add a new column "dbdisplayname" in GN database table "db_webqtl.Temp"

https://github.com/genenetwork/genenetwork/commit/aff993027c035e52a500e5671cb6e4ec564c9c88
