### ISSUE TITLE
Http accessible folder that we can update on one of the penguins

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork#28]
In line with an E-mail I sent last week, can we have a directory exposed to outside, e.g., through http://files.genenetwork.org/. This should reflect a writable directory for the 'gnfiles' group of which I should be member. This is the starting point for deploying data files. This dir should now have 1TB free and may grow out of that in a year when adding raw data. Files going into this dir should contain a SHA value in the name that represent either MD5 or Pfff values.

**Comment by lyan6** [comment]
Hi Pjotr,

Do you think this plan is OK?
1. Create a 1TB partition on another server, and then mount it on Penguin by NFS.
2. Your account on penguin can read/write that partition/directory.
3. Create a public http service (http://files.genenework.org/) which reflects that directory, and anybody can download files from this.

**Comment by pjotrp** [comment]
Fine with me :)

**Comment by pjotrp** [comment]
Where are we on this one? I want to move the genotype files out of the GN2 repo.

**Comment by lyan6** [comment]
The HTTP service is running.

http://files.genenetwork.org/

@penguin:/mnt/big/files.genenetwork.org

**Comment by pjotrp** [comment]
Thanks! Can we also mount this dir on penguin2? GN2 will use it.

**Comment by pjotrp** [comment]
Actually it is fine like this. Thanks and closed!

**Comment by pjotrp** [comment]
It is working great. Are we making backups of this folder? Please close on confirmation.

**Comment by pjotrp** [comment]
It is working great. Are we making backups of this folder? Please close on confirmation.

**Comment by lyan6** [comment]
To build a public rsyncd service which reflects that directory ...

**Comment by lyan6** [comment]
The public rsyncd service is running.

rsync -nah --stats rsync://files.genenetwork.org/gnfiles/

**Comment by lyan6** [comment]
Backups for this folder is done, and an auto script as crontab is running.
