### ISSUE TITLE
GeneNetwork's Time Machine

### ISSUE THREAD

**Issue by lyan6** [genenetwork/genenetwork#32]
http://artemis.uthsc.edu/

**Comment by lyan6** [comment]
To build new version for March 2016.

**Comment by lyan6** [comment]
http://artemis-20160316.genenetwork.org/

**Comment by robwwilliams** [comment]
Thanks much.

This means that we are now in good shape to update GN from mm9 (mouse
assembly) to mm10. I have new genotypes for the BXDs. For the other mouse
genotypes we can just lift-over the genome locations. This will not been
too hard, but it will take a while and Arthur and I will need to error
check (check the order of markers and make sure that the Mb values are in
the right order (from low to high without any inversions of direction).



On Fri, Mar 18, 2016 at 1:42 PM, Lei Yan <notifications@github.com> wrote:

> Closed #32 <https://github.com/genenetwork/genenetwork/issues/32>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/genenetwork/genenetwork/issues/32#event-595313523>
>



-- 
Rob

Robert W. Williams, Ph.D.
UT-ORNL Governor's Chair in Computational Genomics
Chair, Department of Genetics, Genomics and Informatics
University of Tennessee Health Science Center
Room 501
855 Monroe Avenue, Memphis TN 38163 USA

Office 901 448-7018  CELL 901 604 4752
Office: 501 Wittenborg Building
Department of Genetics: 71 Manassas St, Memphis TN 38163
EMAIL: rwilliams@uthsc.edu
Alternative email: labwilliams@gmail.com
SKYPE: robwwilliams
