### ISSUE TITLE
Cannot edit Info

### ISSUE THREAD

**Issue by leiyan** [genenetwork/genenetwork#43]
![image](https://cloud.githubusercontent.com/assets/1719788/18964624/4c8b89e6-863f-11e6-991f-8439082318dd.png)

![image](https://cloud.githubusercontent.com/assets/1719788/18964655/70ed5a12-863f-11e6-8d66-f9f81bce1469.png)

**Comment by lyan6** [comment]
---------- Forwarded message ----------
From: Arthur Centeno <acenteno@gmail.com>
Date: Fri, Sep 30, 2016 at 5:34 PM
Subject: Re: [genenetwork/genenetwork] Cannot edit Info (#43)
To: Lei Yan <leiyan2000@gmail.com>


Hi leiyan,
It's working for me. It's just a password thing. I will ask Rob to reset
his password
Arthur

Sent from my iPhone
